### ISSUE TITLE
Install procedure missing in Makefile

### ISSUE THREAD

**Issue by fyp3180** [Ri0n/rts_bpp#7]
Hey There,
Your code does work but the 'make install' command as explained in the README.txt doesn't. The module is built but is not copied / installed.

There is also a duplicate 'clean" procedure that raises a warning.

It may be worth fixing that.  

I have added :
MOD_DIR=/lib/modules/$(shell uname -r)
and 

install:
	cp $(TARGET_MODULE).ko $(MOD_DIR)/kernel/drivers/scsi -f

to make it work.
Regards

**Comment by Ri0n** [comment]
Hi
I don't have the corresponding hardware anymore. Does it still worth to have this project at all?

**Comment by Ri0n** [comment]
Well after looking the makefile https://github.com/Ri0n/rts_bpp/blob/master/Makefile
I guess you are using some build system which cleans up Makefile somehow.
So the issue is invalid.

**Comment by fyp3180** [comment]
Thank you for your reply. Indeed this is my mistake: I'm new to github and I posted my comment in the wrong place. It was intendend @PythonNut fork (https://github.com/PythonNut/rts_bpp). 
It is still worth having this project open: I bought a laptop 2 years ago and the SD card doesn't work (Ubuntu LTS 18.04)

**Comment by Ri0n** [comment]
What about Ubuntu 20.04?

**Comment by fyp3180** [comment]
I don't know
